### ISSUE TITLE
Unconditional Generation & Image-Conditional Generation

### ISSUE THREAD

**Issue by junsukha** [facebookresearch/ViewDiff#12]
Hi, thanks for sharing the work!

Could you help me with locating the code block that address Image-Conditional Generation section under 3.3 Autoregressive Generation when training?

Is it https://github.com/facebookresearch/ViewDiff/blob/7df36e54728f760a119dac91a1fad01fab0a71aa/viewdiff/train.py#L518 ?

I can't find the code block that address `N = n_c + n_g` of the `Image-Conditional Generation section.

**Comment by junsukha** [comment]
So, to my understanding, you used "Unconditional Generation" and "Image-Conditional Generation" with probabilities p_1 and p_2 as explained in `Training` under 3.4 Implemenation Details, and this part is described in the code block I shared before. 

Also, for inference, if I were to run single image reconstruction, `Image-Conditional Generation` is used as in the code that you shared and eventually `known_images` is later used here:
https://github.com/facebookresearch/ViewDiff/blob/7df36e54728f760a119dac91a1fad01fab0a71aa/viewdiff/model/custom_stable_diffusion_pipeline.py#L704
I suppose that `latents[:n_known_images] = known_image_latents` is related to `n_c`. Timesteps are set to 0 for these known images in unet forward function.

By the way, "Unconditional Generation" under 3.3 Autoregressive Generation means that no images are used as condition? It says "... a single text prompt" is used. I was a bit confused why it's called "Unconditonal" although it uses a text prompt.

**Comment by lukasHoel** [comment]
Yes this is all correct. Yeah unconditional refers to no image as input, but still a text prompt can be provided
