### ISSUE TITLE
Autoregressive generation when n_c = 1

### ISSUE THREAD

**Issue by junsukha** [facebookresearch/ViewDiff#13]
Hi, thanks for sharing the work!

The paper says 

> When nc=1, our method performs single-image reconstruction (Fig. 6). Setting nc>1 allows to autoregressively generate novel views from previous images (Fig. 1 bottom). In practice, we first generate one batch of images unconditionally and then condition the next batches on a subset of previous images.

So you don't use autoregressive generation when a task is single image reconstruction?

If so, may I ask why didn't use autoregressive method when nc=1?

Thanks!

**Comment by lukasHoel** [comment]
Hi, we use n_c=1 only for the first batch in single image reconstruction. After that we use all (or a subset of) previously generated images (autoregressive generation)

**Comment by junsukha** [comment]
@lukasHoel oh so the difference between when the number of input image is 1  (single image reconstruction) and when more than 1 is that n_c = 1 for the former case while n_c > 1 for the latter case in the first batch? After the first batch, n_c > 1 for both cases to use autoregressive generation.

**Comment by lukasHoel** [comment]
Yes that's correct
