### ISSUE TITLE
pipeline question / paper question

### ISSUE THREAD

**Issue by sararoma95** [facebookresearch/ViewDiff#16]
<img width="897" alt="Screenshot 2024-05-07 at 14 12 57" src="https://github.com/facebookresearch/ViewDiff/assets/95563069/8187aa85-af0d-4678-935c-dcbeb67d9a60">
Hello,

I’m reviewing the network proposed in your paper for rendering multiple images from a single/two images. I noticed in the pipeline diagram that the input and output images seem swapped between the top and bottom parts. Is this arrangement intentional, or could it be a diagram error?

Could you clarify:

1. Whether the image arrangement in the diagram is intentional.
2. The reasoning behind this configuration, if it's intentional.

Thank you for your help and for the interesting paper.

**Comment by lukasHoel** [comment]
Hi, thanks for the question. It's a slight inaccuracy in the pipeline figure. We compare the predicted and sampled noise for the same image.

**Comment by sararoma95** [comment]
Thanks
