### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by ShengyuH** [facebookresearch/ViewDiff#8]
hi, 

Thanks for sharing this great work. I have one question about the train/validation/test split. I can only get vague information about such split from the supplementary: "With probability p=0.5 we select the training images randomly per object and with probability p 2 =0.5 we select consecutive images from the captured trajectory that goes around the object." Does this mean that the train and test samples come from the same scene? Or are they actually strictly different, i.e., test scenes (used in Table 1) are never seen during training? 

Looking forward to your reply.

best,
Shengyu

**Comment by lukasHoel** [comment]
Hi, train and test objects are disjoint, i.e., test input (prompts,
cameras, intrinsic, images) were not sampled during training. The
description that you cited refers to the sampling strategy for a single
object during training.

Shengyu HUANG ***@***.***> schrieb am So., 17. März 2024,
14:44:
