### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by yijicheng** [facebookresearch/ViewDiff#9]
Could you show which subset and split you used for training and testing? Subset and split are not set in train.sh.

**Comment by lukasHoel** [comment]
We provide a small wrapper around the default CO3D dataloader in https://github.com/facebookresearch/ViewDiff/blob/main/viewdiff/data/co3d/co3d_dataset.py.

Therefore, it is possible to use all the arguments that are provided by the original dataloader to select train/test splits.
For example, there is the ```--subset``` and ```--split``` option. Please see [here](https://github.com/facebookresearch/co3d) for more details and explanations of the available arguments.

As default in the released code, we select ```N=[500, 1000]``` random sequences for training **without using any predefined subsets or splits from the dataset**.
The testing sequences are then drawn from the remaining sequences.

For comparisons to baselines (e.g., what we did in the paper) it's recommend to specify a  ```--subset``` and ```--split``` option that is identical to the options found in those methods and train with that.

**Comment by yijicheng** [comment]
Thanks for you answer!
